volumes:
  demo_postgres_data:
    external: true


networks:
  default:
    name: demo
    external: true


services:
  backend:
    image: local/demo_backend
    platform: linux/amd64
    build:
      dockerfile: backend/Dockerfile
      args:
        - UID=${UID:?err}
        - GID=${GID:?err}
    env_file: [ .env ]
    volumes: [ ./backend:/app:rw ]
    networks:
      default:
        aliases: [ demo-backend ]
    command: [ 'fastapi', 'run' ]

  db:
    image: postgres:14.13-bookworm
    platform: linux/amd64
    env_file: [ .env ]
    volumes:
      - demo_postgres_data:/var/lib/postgresql:rw
      - ./db:/app
    networks:
      default:
        aliases: [ demo-db ]
    ports:
      - ${EXPOSE_DB_PORT:?5432}:5432

  frontend:
    image: node:22-bookworm
    platform: linux/amd64
    env_file: [ .env ]
    volumes: [ ./frontend:/app:rw ]
    ports:
      - ${WDS_SOCKET_PORT:?3000}:3000
    networks:
      default:
        aliases: [ demo-frontend ]
    command: [ 'npm', 'start' ]
    working_dir: /app

  gateway:
    image: nginx:1.26-bookworm-perl
    ports:
      - ${EXPOSE_API_PORT:?8000}:80
    volumes:
      - ./gateway/logs:/var/log/nginx:rw
      - ./gateway/conf.d:/etc/nginx/conf.d:rw
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on: [ backend, frontend ]
    restart: always
