server {
    listen 80;
    server_name demo.loc;

    location /api/ {
        proxy_pass http://demo-backend:8000/api/;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    location / {
        proxy_pass http://demo-frontend:3000/;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
